services:
  yolo-detector:
    build: .
    container_name: yolo_app
    volumes:
      - ./app:/app
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5001:5001"